on:
  pull_request:
    branches: [ main ]
  push:
    branches:
     - main

jobs:
  client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Gradle build
      run: gradle build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: loader-client
        path: |
          client/build/libs/*
